### ISSUE TITLE
Algunas correcciones

### ISSUE THREAD

**Issue by mjaque** [JaimeSilvestre/chaterito#1]
En el fichero html, tienes que sacar el input del name del div de chat.
Y tienes que poner el mismo nombre al div de borde en el fichero html y en el css, sino no se aplican las reglas de estilo (por eso se muestra mal el html).
Y de paso, sube el fichero de index.js

**Comment by JaimeSilvestre** [comment]
no hay error , eso es cosa de los demoni0s maldit0s de uweduwenwe
